function q_tilde_from_q = q_tilde_from_q_gen(qs, gait_params)
%Q_TILDE_FROM_Q_GEN
%    Q_TILDE_FROM_Q = Q_TILDE_FROM_Q_GEN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    05-Dec-2021 17:20:46

beta1 = gait_params(1,:);
beta2 = gait_params(2,:);
beta3 = gait_params(3,:);
beta4 = gait_params(4,:);
q1 = qs(3,:);
q2 = qs(4,:);
th1d = gait_params(5,:);
x = qs(1,:);
ypos = qs(2,:);
q_tilde_from_q = [x;ypos;q1.*2.0+q2-(q1+th1d).*(q1-th1d).*(beta1+beta2.*q1+beta3.*q1.^2+beta4.*q1.^3);q1];
